DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS farmer_profiles;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20) NOT NULL UNIQUE,
    address VARCHAR(255),
    avatar VARCHAR(255) DEFAULT '/images/common/头像.jpg',
    role VARCHAR(10) NOT NULL CHECK (role IN ('USER', 'ADMIN', 'FARMER')) DEFAULT 'USER',
    status INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE farmer_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    farm_name VARCHAR(100),
    address VARCHAR(255),
    id_card_img VARCHAR(255),
    intro TEXT,
    audit_status VARCHAR(10) NOT NULL CHECK (audit_status IN ('PENDING', 'APPROVED', 'REJECTED')) DEFAULT 'PENDING',
    audit_time TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    stock INT NOT NULL,
    image VARCHAR(255),
    origin VARCHAR(100),
    sales INT DEFAULT 0,
    farmer_id BIGINT,
    audit_status VARCHAR(10) NOT NULL CHECK (audit_status IN ('PENDING', 'APPROVED', 'REJECTED')) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (farmer_id) REFERENCES farmer_profiles(id) ON DELETE SET NULL
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) DEFAULT 'PENDING',
    shipping_address VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- Updated initial data with phone numbers
INSERT INTO users (username, password, phone, email, role, status) VALUES
('admin', '$2a$10$E.qJ4s5.g6i5a/L.N.L4/uP.U.e2q9.a/s5fS6.d5gD3.h/eW6a', '18888888888', 'admin@licha.com', 'ADMIN', 1),
('user1', '$2a$10$E.qJ4s5.g6i5a/L.N.L4/uP.U.e2q9.a/s5fS6.d5gD3.h/eW6a', '13800138000', 'user1@licha.com', 'USER', 1),
('farmer1', '$2a$10$E.qJ4s5.g6i5a/L.N.L4/uP.U.e2q9.a/s5fS6.d5gD3.h/eW6a', '15800158000', 'farmer1@licha.com', 'FARMER', 1);

INSERT INTO farmer_profiles (user_id, farm_name, address, intro, audit_status) VALUES
(3, '王大伯的有机茶园', '湖北省恩施土家族苗族自治州利川市毛坝镇', '世代种茶，手工制茶，只为一杯好茶。', 'APPROVED');

INSERT INTO products (name, description, price, stock, image, origin, sales, farmer_id, audit_status) VALUES
('利川红茶-清风', '初春采摘，滋味鲜爽', 199.00, 100, '/images/products/product1.jpg', '湖北利川', 50, 1, 'APPROVED'),
('利川红茶-明月', '谷雨时节，香气醇厚', 299.00, 80, '/images/products/product2.jpg', '湖北利川', 30, 1, 'APPROVED');
